/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nerdgame;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author aggeliki
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form gui2
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new javax.swing.JButton();
        ImageIcon myImage = new ImageIcon("/Images/Signup_Default.png");
        SignupButton = new javax.swing.JButton(myImage);
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nerd Game");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GUI/Login.png"))); // NOI18N
        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginButtonMouseReleased(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(370, 230, 110, 40);

        SignupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GUI/SignUp.png"))); // NOI18N
        SignupButton.setBorderPainted(false);
        SignupButton.setContentAreaFilled(false);
        SignupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignupButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SignupButtonMouseReleased(evt);
            }
        });
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignupButton);
        SignupButton.setBounds(370, 290, 110, 40);

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GUI/Exit.png"))); // NOI18N
        ExitButton.setBorderPainted(false);
        ExitButton.setContentAreaFilled(false);
        ExitButton.setLabel("");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitButtonMouseReleased(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(20, 323, 110, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TestLogo2.png"))); // NOI18N
        jLabel1.setText("Welcome!");
        jLabel1.setPreferredSize(new java.awt.Dimension(325, 260));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 0, 310, 190);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mathematics-wallpaper.png"))); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(600, 500));
        Background.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 640, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //IMAGES
    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/LoginHover.png"));
        LoginButton.setIcon(df);    
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/Login.png"));
        LoginButton.setIcon(df);
    }//GEN-LAST:event_LoginButtonMouseExited

    private void LoginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMousePressed
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/LoginPressed.png"));
        LoginButton.setIcon(df);
    }//GEN-LAST:event_LoginButtonMousePressed

    private void LoginButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseReleased
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/LoginHover.png"));
        LoginButton.setIcon(df);
    }//GEN-LAST:event_LoginButtonMouseReleased

    private void SignupButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseEntered
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/SignUpHover.png"));
        SignupButton.setIcon(df);
    }//GEN-LAST:event_SignupButtonMouseEntered

    private void SignupButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseExited
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/SignUp.png"));
        SignupButton.setIcon(df);
    }//GEN-LAST:event_SignupButtonMouseExited

    private void SignupButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMousePressed
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/SignUpPressed.png"));
        SignupButton.setIcon(df);
    }//GEN-LAST:event_SignupButtonMousePressed

    private void SignupButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseReleased
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/SignUpHover.png"));
        SignupButton.setIcon(df);
    }//GEN-LAST:event_SignupButtonMouseReleased

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        
        login.setSize(350, 500);
        login.setLocationRelativeTo(null);
        
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setVisible(false);
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        SignupGUI signup = new SignupGUI();
        signup.setVisible(true);
        
        signup.setSize(350, 500);
        signup.setLocationRelativeTo(null);
        
        signup.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setVisible(false);
        dispose();
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    
    //IMAGES
    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/ExitHover.png"));
        ExitButton.setIcon(df);
    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/Exit.png"));
        ExitButton.setIcon(df);
    }//GEN-LAST:event_ExitButtonMouseExited

    private void ExitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMousePressed
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/ExitPressed.png"));
        ExitButton.setIcon(df);
    }//GEN-LAST:event_ExitButtonMousePressed

    private void ExitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseReleased
        ImageIcon df = new ImageIcon(getClass().getResource("/Images/GUI/ExitHover.png"));
        ExitButton.setIcon(df);
    }//GEN-LAST:event_ExitButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
