/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nerdgame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aggeliki
 */
public class SignupGUI extends javax.swing.JFrame {

    
    //initialize connections with database
  Connection con = null;
  ResultSet rs = null;
  PreparedStatement pst = null;
  
  
    public SignupGUI() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        nameFieldUser = new javax.swing.JTextField();
        EducationUser = new javax.swing.JTextField();
        NicknameUserField = new javax.swing.JTextField();
        DepartmentFieldUser = new javax.swing.JTextField();
        PasswordUser = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SignupButtonSignupGUI = new javax.swing.JButton();
        BackButtonSignupGUI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setSize(new java.awt.Dimension(350, 500));
        getContentPane().setLayout(null);
        getContentPane().add(nameFieldUser);
        nameFieldUser.setBounds(200, 20, 90, 20);
        getContentPane().add(EducationUser);
        EducationUser.setBounds(200, 120, 90, 20);
        getContentPane().add(NicknameUserField);
        NicknameUserField.setBounds(200, 220, 90, 20);
        getContentPane().add(DepartmentFieldUser);
        DepartmentFieldUser.setBounds(200, 170, 90, 20);
        getContentPane().add(PasswordUser);
        PasswordUser.setBounds(200, 70, 90, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 80, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Univeristy");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 80, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nickname");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 220, 70, 20);

        SignupButtonSignupGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GUI/SignUp.png"))); // NOI18N
        SignupButtonSignupGUI.setBorderPainted(false);
        SignupButtonSignupGUI.setContentAreaFilled(false);
        SignupButtonSignupGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupButtonSignupGUIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupButtonSignupGUIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignupButtonSignupGUIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SignupButtonSignupGUIMouseReleased(evt);
            }
        });
        SignupButtonSignupGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonSignupGUIActionPerformed(evt);
            }
        });
        getContentPane().add(SignupButtonSignupGUI);
        SignupButtonSignupGUI.setBounds(190, 400, 110, 50);

        BackButtonSignupGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login/Back_Default.png"))); // NOI18N
        BackButtonSignupGUI.setBorderPainted(false);
        BackButtonSignupGUI.setContentAreaFilled(false);
        BackButtonSignupGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButtonSignupGUIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButtonSignupGUIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackButtonSignupGUIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackButtonSignupGUIMouseReleased(evt);
            }
        });
        BackButtonSignupGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonSignupGUIActionPerformed(evt);
            }
        });
        getContentPane().add(BackButtonSignupGUI);
        BackButtonSignupGUI.setBounds(50, 400, 80, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Signup/cartoon3.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 260, 124, 130);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mathematics-wallpaper.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 340, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonSignupGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonSignupGUIActionPerformed
        dispose();
        
        GUI gui = new GUI();
        
        gui.setVisible(true);
        
        gui.setSize(350, 500);
        
        gui.setLocationRelativeTo(null);
        
        gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BackButtonSignupGUIActionPerformed

    private void SignupButtonSignupGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonSignupGUIActionPerformed
        //User interface
        String department = DepartmentFieldUser.getText();
        String password = PasswordUser.getText();
        String nickname = NicknameUserField.getText();
        String username = nameFieldUser.getText();
        String education = EducationUser.getText();
        String rating = "0";
        String highscore = "0";
        
        LoginGUI.un = username;
        if( username.isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Username error");
        }
        else if(password.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Password error");
        }
        else if (department.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Department error");
        }
        else if (nickname.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nickname error");
        }
        else if (education.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "University error");
        }
        else
        {
        String sql = "insert into user(Username,Password,Nickname,University,Department,Rating,Highscore) value (?,?,?,?,?,?,?)";
        
         try
         {

             //Server

        Class.forName("java.sql.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull","root","8520");
        pst = con.prepareStatement(sql);
    
        pst.setString(1, username);
        pst.setString(2, password);
        pst.setString(3, nickname);
        pst.setString(4, education);
        pst.setString(5, department);
        pst.setString(6, rating);
        pst.setString(7, highscore);
        
        pst.execute();
        dispose();
            ModeGUI mgui = new ModeGUI();
            mgui.setVisible(true);
        
            mgui.setSize(400, 500);
            mgui.setLocationRelativeTo(null);
        
            mgui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
        catch(Exception e)
        {   
            JOptionPane.showMessageDialog(null,"Nickname or Username is already taken from another user, try another.");
        }
      }                                                     
    }//GEN-LAST:event_SignupButtonSignupGUIActionPerformed

    
    //IMAGES
    private void SignupButtonSignupGUIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonSignupGUIMouseEntered
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/GUI/SignUpHover.png"));
        SignupButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_SignupButtonSignupGUIMouseEntered

    private void SignupButtonSignupGUIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonSignupGUIMouseExited
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/GUI/SignUp.png"));
        SignupButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_SignupButtonSignupGUIMouseExited

    private void SignupButtonSignupGUIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonSignupGUIMousePressed
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/GUI/SignUpPressed.png"));
        SignupButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_SignupButtonSignupGUIMousePressed

    private void SignupButtonSignupGUIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonSignupGUIMouseReleased
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/GUI/SignUpHover.png"));
        SignupButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_SignupButtonSignupGUIMouseReleased

    private void BackButtonSignupGUIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonSignupGUIMouseEntered
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/Login/Back_Hover.png"));
        BackButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_BackButtonSignupGUIMouseEntered

    private void BackButtonSignupGUIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonSignupGUIMouseExited
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/Login/Back_Default.png"));
        BackButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_BackButtonSignupGUIMouseExited

    private void BackButtonSignupGUIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonSignupGUIMousePressed
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/Login/Back_Pressed.png"));
        BackButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_BackButtonSignupGUIMousePressed

    private void BackButtonSignupGUIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonSignupGUIMouseReleased
        ImageIcon su = new ImageIcon(getClass().getResource("/Images/Login/Back_Hover.png"));
        BackButtonSignupGUI.setIcon(su);
    }//GEN-LAST:event_BackButtonSignupGUIMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtonSignupGUI;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField DepartmentFieldUser;
    private javax.swing.JTextField EducationUser;
    private javax.swing.JTextField NicknameUserField;
    private javax.swing.JPasswordField PasswordUser;
    private javax.swing.JButton SignupButtonSignupGUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField nameFieldUser;
    // End of variables declaration//GEN-END:variables
}
